#ifndef SOCKS5_BASE_H
#define SOCKS5_BASE_H

#define SOCKS5_VERSION (char)0x05

#define SOCKS_STATUS_WAIT_DISCONNECT -2
#define SOCKS_STATUS_REMOTE -1
#define SOCKS_STATUS_NONE 0
#define SOCKS_STATUS_METHODS 1
#define SOCKS_STATUS_METHODS_RESPONSE 2
#define SOCKS_STATUS_AUTH 3
#define SOCKS_STATUS_AUTH_RESPONSE 4
#define SOCKS_STATUS_CONNECT 5
#define SOCKS_STATUS_DONE 6

#define SOCKS5_METHOD_NO_AUTHENTICATION_REQUIRED 0x00
#define SOCKS5_METHOD_USERNAME_PASSWORD 0x02
#define SOCKS5_METHOD_KCP_NO_AUTHENTICATION_REQUIRED 0xA0
#define SOCKS5_METHOD_KCP_USERNAME_PASSWORD 0xA2
#define SOCKS5_METHOD_NO_ACCEPTABLE_METHODS 0xFF

#define IPV4_LEN 4
#define IPV6_LEN 16
#define PORT_LEN 2
#define MAX_DOMAIN_LEN 255
#define SOCKS5_CONN_HEADER_LEN 4
#define MAX_IPV4_ADDRESS_LEN 21
#define MAX_IPV6_ADDRESS_LEN 39

#define SOCKS5_CMD_CONNECT (char)0x01

#define SOCKS5_ATYPE_IPV4 (char)0x01
#define SOCKS5_ATYPE_DOMAINNAME (char)0x03
#define SOCKS5_ATYPE_IPV6 (char)0x04

#define SOCKS5_REPLY_SUCCEEDED (char)0x00
#define SOCKS5_REPLY_GENERAL_SOCKS_SERVER_FAILURE (char)0x01
#define SOCKS5_REPLY_CONNECTION_NOT_ALLOWED_BY_RULESET (char)0x02
#define SOCKS5_REPLY_NETWORK_UNREACHABLE (char)0x03
#define SOCKS5_REPLY_HOST_UNREACHABLE (char)0x04
#define SOCKS5_REPLY_CONNECT_REFUSED (char)0x05
#define SOCKS5_REPLY_TTL_EXPIRED (char)0x06
#define SOCKS5_REPLY_COMMAND_NOT_SUPPORTED (char)0x07
#define SOCKS5_REPLY_ADDRESS_TYPE_NOT_SUPPORTED (char)0x08

// reply ext
#define SOCKS5_REPLY_EXT_AUTH_FAILED (char)0xA0


#define SOCKS_TYPE_CLIENT 0
#define SOCKS_TYPE_REMOTE 1

#define SOCKS_USERNAME_PASSWORD_AUTH_VERSION_1 0x01
#define SOCKS_USERNAME_PASSWORD_AUTH_SUCCESS 0x00

#endif // SOCKS5_BASE_H